version: "3"
services:
  seeds_api:
    build: ./api
    container_name: "seeds_api"
    ports:
      - "3000:3000"
    command: bash -c "bundle exec pumactl start"
    volumes:
      - ./api:/myapp
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=ON
    env_file:
      - seeds.env

  seeds_view:
    build: ./view
    container_name: "seeds_view"
    ports:
      - 8080:8080
    command: bash -c "npm run start"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - SEEDS_API_URI=https://seeds-api.nutfes.net
      - NODE_ENV=production

  # 定期実行用コンテナ
  cron:
    image: nutmeg-seeds_seeds_api:latest
    command: >
      sh -c "whenever --update-cron &&
      cron -f -l 2"
    restart: always
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - seeds_api

  seeds_minio:
    image: quay.io/minio/minio:latest
    container_name: seeds_minio
    environment:
      MINIO_ROOT_USER: nutmeg
      MINIO_ROOT_PASSWORD: gidaifes
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/export
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-data:
    driver: local
  code_share:
