version: "3"
services:
  seeds_db:
    image: mysql:8.0
    container_name: "seeds_db"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  seeds_api:
    build: ./api
    container_name: "seeds_api"
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - ./api:/myapp
    depends_on:
      - seeds_db
    stdin_open: true
    tty: true

  seeds_view:
    build: ./view
    container_name: "seeds_view"
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - SEEDS_API_URI=http://localhost:3000

  # 定期実行用コンテナ
  cron:
    image: nutmeg-seeds-seeds_api:latest
    command: >
      sh -c "whenever --update-cron &&
      cron -f -l 2"
    restart: always
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - seeds_api

  seeds_minio:
    image: quay.io/minio/minio:latest
    container_name: seeds_minio
    environment:
      MINIO_ROOT_USER: nutmeg
      MINIO_ROOT_PASSWORD: gidaifes
    entrypoint: sh
    command: -c "/usr/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/export
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-data:
    driver: local
