version: "3"
services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: "seeds_cloudflare"
    volumes:
      - ./cloudflare/prod:/home/nonroot/.cloudflared
    command: tunnel run

  seeds_api:
    build: ./api
    container_name: "seeds_api"
    ports:
      - "3000:3000"
    command: bash -c "bundle exec pumactl start"
    volumes:
      - ./api:/myapp
    stdin_open: true
    tty: true
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=ON
    env_file:
      - seeds.env

  seeds_view:
    build: ./view
    container_name: "seeds_view"
    ports:
      - 8080:8080
    command: bash -c "npm run start"
    volumes:
      - ./view:/app
      - ./view/next-project/node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - SEEDS_API_URI=https://seeds-api.nutfes.net
      - NODE_ENV=production

  # 定期実行用コンテナ
  cron:
    image: nutmeg-seeds-seeds_api:latest
    command: >
      sh -c "whenever --update-cron &&
      cron -f -l 2"
    restart: always
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - seeds_api

volumes:
  mysql-data:
    driver: local
  code_share:
