version: '3'
services:
  seeds_api:
    build: ./api
    container_name: 'seeds_api'
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    volumes:
      - ./api:/myapp
    stdin_open: true
    tty: true
    environment: 
      - RAILS_ENV=production
    env_file:
      - nutmeg-mysql.env

  seeds_view: 
    build: ./view
    container_name: 'seeds_view'
    ports: 
      - "8080:8080"
        #command: npm run build && npm run start
    volumes:
      - ./view:/app
    stdin_open: true
    tty: true
    environment:
      - SEEDS_API_URI=https://seeds-api.nutfes.net

volumes:
  mysql-data:
    driver: local
  code_share: 
