version: "3"
services:
  seeds_db:
    image: postgres:12
    volumes:
      - mysql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_development
      POSTGRES_USER: seeds
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

  seeds_api:
    build: ./api
    container_name: "seeds_api"
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - ./api:/myapp
    depends_on:
      seeds_db:
        condition: service_started

  seeds_view:
    build: ./view
    container_name: "seeds_view"
    ports:
      - "8080:8080"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./view:/app
    environment:
      - SEEDS_API_URI=http://localhost:3000
    depends_on:
      seeds_api:
        condition: service_started

volumes:
  mysql-data:
    driver: local
