import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const Title = styled.h1`
  color: var(--text-secondary);
`
const TitleContainer = styled.div`
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NUTMEG Seeds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>NUTMEG</Title>
    </div>
  )
}

export default Home
